### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ZhL0b1X** [N0rz3/Zehef#1]
Here is the error:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

OS: MacOS Monterey

**Comment by N0rz3** [comment]
hi where are you getting this error?

**Comment by N0rz3** [comment]
when you run the script? or during the launch of a function? ...

**Comment by ZhL0b1X** [comment]
> when you run the script? or during the launch of a function? ...
 
python3 zehef.py example@example.com

Error occure after line:
 Leak / Breach

**Comment by ZhL0b1X** [comment]
[2023-06-15 22:34:29] Error : Ratelimit, please change your ip.

**Comment by N0rz3** [comment]
oke, did you install the requirements correctly? If not, install them. And for the ratelimit well it's normal, you just have to change your ip and the script will work again

**Comment by ZhL0b1X** [comment]
> oke, did you install the requirements correctly? If not, install them. And for the ratelimit well it's normal, you just have to change your ip and the script will work again


pip3 install -r requirements.txt

Everything installed just fine. 
Actually i have tried to change my IP already. 
Same thing unfortunately.

**Comment by N0rz3** [comment]
If everything is installed correctly, I'm sorry but I have no idea. Already it's an error related to urllib except that I don't use this library. So either it's an error in a module that is mandatory for the proper functioning of the script, or it's an error on your side.

**All the same I apologize if it's not on your side because I don't see at all why this error occurs**

**Comment by N0rz3** [comment]
(I never had this problem nor people who used the tool.) It may be due to your bone (this remains deduction)

**Comment by TimTProd** [comment]
well this problem, I think, occurs only on macOS. To solve it, go to the /Applications folder, then Python folder and run "Install Certificates.command". But it only works if you installed python via their site. If you installed python via maports or homebrew then there will be another solution (google)

**Comment by ZhL0b1X** [comment]
> well this problem, I think, occurs only on macOS. To solve it, go to the /Applications folder, then Python folder and run "Install Certificates.command". But it only works if you installed python via their site. If you installed python via maports or homebrew then there will be another solution (google)


I'll try it. Thanks pal!
