### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [N0rz3/Zehef#13]
It worked first after...
![image](https://github.com/N0rz3/Zehef/assets/71973368/03394c98-f1f2-4bcd-ab27-dbd3f0032f86)

**Comment by alexnicco98** [comment]
You should update the file "AppData\Local\Programs\Python\Python312\Lib\site-packages\holehe\modules\programing\github.py" with: 
`from holehe.core import *
from holehe.localuseragent import *
import re


async def github(email, client, out):
    name = "github"
    domain = "github.com"
    method = "register"
    frequent_rate_limit = False

    freq = await client.get("https://github.com/join")
    token_regex = re.compile(
        r'<auto-check src="/signup_check/username[\s\S]*?value="([\S]+)"[\s\S]*<auto-check src="/signup_check/email[\s\S]*?value="([\S]+)"'
    )
    token = token_regex.findall(freq.text)

    if not token:
        out.append({
            "name": name,
            "domain": domain,
            "method": method,
            "frequent_rate_limit": frequent_rate_limit,
            "rateLimit": True,
            "exists": None,
            "emailrecovery": None,
            "phoneNumber": None,
            "others": None
        })
        return

    data = {"value": email, "authenticity_token": token[0][0]}
    req = await client.post("https://github.com/signup_check/email", data=data)

    if "Your browser did something unexpected." in req.text:
        out.append({
            "name": name,
            "domain": domain,
            "method": method,
            "frequent_rate_limit": frequent_rate_limit,
            "rateLimit": True,
            "exists": None,
            "emailrecovery": None,
            "phoneNumber": None,
            "others": None
        })
    elif req.status_code == 422:
        out.append({
            "name": name,
            "domain": domain,
            "method": method,
            "frequent_rate_limit": frequent_rate_limit,
            "rateLimit": False,
            "exists": True,
            "emailrecovery": None,
            "phoneNumber": None,
            "others": None
        })
    elif req.status_code == 200:
        out.append({
            "name": name,
            "domain": domain,
            "method": method,
            "frequent_rate_limit": frequent_rate_limit,
            "rateLimit": False,
            "exists": False,
            "emailrecovery": None,
            "phoneNumber": None,
            "others": None
        })
    else:
        out.append({
            "name": name,
            "domain": domain,
            "method": method,
            "frequent_rate_limit": frequent_rate_limit,
            "rateLimit": True,
            "exists": None,
            "emailrecovery": None,
            "phoneNumber": None,
            "others": None
        })`

**Comment by N0rz3** [comment]
With v2 of Zehef no more bugs to be reported (at least I think)
