### ISSUE TITLE
Hudson Rock Cybercrime Intelligence Free Integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [N0rz3/Zehef#15]
Consider adding Hudson Rock's complimentary data to receive additional intelligence about the email address that was compromised in global Infostealer attacks.

Email sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com

Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs

Thank you.

**Comment by N0rz3** [comment]
Good evening, thank you for this great idea. I looked at what you are offering and I am currently in the process of developing the tool (obtaining more information on targeted email). I will add your service soon.

**Comment by hudsonrock-partnerships** [comment]
You're welcome and thank you for checking this issue. 
Feel free to reach out for any additional questions or clarifications.

**Comment by N0rz3** [comment]
I just added your service to Zehef, thank you for letting me know about it 👍
